import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';
import { jsPDF } from 'npm:jspdf@2.5.2';

// Helper: hex to RGB
function hexToRgb(hex) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex || '#111827');
  return result ? {
    r: parseInt(result[1], 16),
    g: parseInt(result[2], 16),
    b: parseInt(result[3], 16)
  } : { r: 17, g: 24, b: 39 };
}

// Draw a horizontal rule
function drawRule(doc, x, y, width, color) {
  const rgb = hexToRgb(color);
  doc.setDrawColor(rgb.r, rgb.g, rgb.b);
  doc.setLineWidth(0.5);
  doc.line(x, y, x + width, y);
}

// Draw header section
function drawHeader(doc, template, pageWidth, margin) {
  const { branding = {}, header = {} } = template;
  const primaryRgb = hexToRgb(branding.primary_color || '#111827');
  const secondaryRgb = hexToRgb(branding.secondary_color || '#6B7280');
  let y = margin;

  // Logo placeholder or company name block
  if (header.company_name) {
    doc.setFontSize(20);
    doc.setFont(branding.font || 'helvetica', 'bold');
    doc.setTextColor(primaryRgb.r, primaryRgb.g, primaryRgb.b);
    doc.text(header.company_name, margin, y);
    y += 7;
  }

  if (header.tagline) {
    doc.setFontSize(9);
    doc.setFont(branding.font || 'helvetica', 'italic');
    doc.setTextColor(secondaryRgb.r, secondaryRgb.g, secondaryRgb.b);
    doc.text(header.tagline, margin, y);
    y += 5;
  }

  // Right-aligned contact info
  const contactLines = [];
  if (header.address) contactLines.push(header.address);
  if (header.phone) contactLines.push(header.phone);
  if (header.email) contactLines.push(header.email);
  if (header.website) contactLines.push(header.website);

  if (contactLines.length > 0) {
    doc.setFontSize(8);
    doc.setFont(branding.font || 'helvetica', 'normal');
    doc.setTextColor(secondaryRgb.r, secondaryRgb.g, secondaryRgb.b);
    const startY = margin;
    contactLines.forEach((line, i) => {
      const textWidth = doc.getTextWidth(line);
      doc.text(line, pageWidth - margin - textWidth, startY + i * 4.5);
    });
  }

  if (header.show_date !== false) {
    const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    doc.setFontSize(8);
    doc.setTextColor(secondaryRgb.r, secondaryRgb.g, secondaryRgb.b);
    const tw = doc.getTextWidth(dateStr);
    doc.text(dateStr, pageWidth - margin - tw, margin + (contactLines.length * 4.5) + 5);
  }

  const headerBottom = Math.max(y + 2, margin + 20);
  drawRule(doc, margin, headerBottom, pageWidth - margin * 2, branding.primary_color || '#111827');
  return headerBottom + 6;
}

// Draw footer on a page
function drawFooter(doc, template, pageWidth, pageHeight, margin, pageNum, totalPages) {
  const { branding = {}, footer = {} } = template;
  const secondaryRgb = hexToRgb(branding.secondary_color || '#6B7280');
  const footerY = pageHeight - margin + 4;

  drawRule(doc, margin, footerY - 6, pageWidth - margin * 2, branding.secondary_color || '#6B7280');

  doc.setFontSize(8);
  doc.setTextColor(secondaryRgb.r, secondaryRgb.g, secondaryRgb.b);
  doc.setFont(branding.font || 'helvetica', 'normal');

  if (footer.text) {
    doc.text(footer.text, margin, footerY);
  }

  if (footer.show_generated_by !== false) {
    const genText = 'Generated by Platform';
    const genW = doc.getTextWidth(genText);
    doc.text(genText, (pageWidth - genW) / 2, footerY);
  }

  if (footer.show_page_numbers !== false) {
    const pageText = `Page ${pageNum} of ${totalPages}`;
    const tw = doc.getTextWidth(pageText);
    doc.text(pageText, pageWidth - margin - tw, footerY);
  }
}

// Render a key-value section
function renderSection(doc, title, rows, startY, pageWidth, margin, branding) {
  const primaryRgb = hexToRgb(branding.primary_color || '#111827');
  const secondaryRgb = hexToRgb(branding.secondary_color || '#6B7280');
  let y = startY;

  // Section title
  doc.setFillColor(primaryRgb.r, primaryRgb.g, primaryRgb.b);
  doc.rect(margin, y - 4, pageWidth - margin * 2, 8, 'F');
  doc.setFontSize(9);
  doc.setFont(branding.font || 'helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text(title.toUpperCase(), margin + 3, y + 1);
  y += 8;

  // Rows
  let rowEven = true;
  for (const row of rows) {
    if (!row) continue;
    if (rowEven) {
      doc.setFillColor(248, 249, 250);
      doc.rect(margin, y - 3, pageWidth - margin * 2, 7, 'F');
    }
    doc.setFontSize(9);
    doc.setFont(branding.font || 'helvetica', 'bold');
    doc.setTextColor(secondaryRgb.r, secondaryRgb.g, secondaryRgb.b);
    doc.text(String(row.label) + ':', margin + 3, y + 1);
    doc.setFont(branding.font || 'helvetica', 'normal');
    doc.setTextColor(17, 24, 39);
    const valueStr = row.value != null ? String(row.value) : '—';
    // Wrap long values
    const maxWidth = (pageWidth - margin * 2) * 0.55;
    const lines = doc.splitTextToSize(valueStr, maxWidth);
    doc.text(lines, margin + (pageWidth - margin * 2) * 0.4, y + 1);
    const lineHeight = Math.max(lines.length * 5, 7);
    y += lineHeight;
    rowEven = !rowEven;
  }

  return y + 4;
}

// Build a Job PDF
function buildJobPDF(doc, job, customer, template, pageWidth, pageHeight, margin) {
  const { branding = {} } = template;
  const primaryRgb = hexToRgb(branding.primary_color || '#111827');
  const secondaryRgb = hexToRgb(branding.secondary_color || '#6B7280');

  let y = drawHeader(doc, template, pageWidth, margin);

  // Document title
  doc.setFontSize(16);
  doc.setFont(branding.font || 'helvetica', 'bold');
  doc.setTextColor(primaryRgb.r, primaryRgb.g, primaryRgb.b);
  doc.text('JOB DETAILS', margin, y);
  y += 4;

  doc.setFontSize(10);
  doc.setFont(branding.font || 'helvetica', 'normal');
  doc.setTextColor(secondaryRgb.r, secondaryRgb.g, secondaryRgb.b);
  doc.text(job.reference_number || 'N/A', margin, y + 4);
  y += 12;

  // Overview section
  y = renderSection(doc, 'Overview', [
    { label: 'Title', value: job.title },
    { label: 'Status', value: (job.status || '').replace(/_/g, ' ').toUpperCase() },
    { label: 'Priority', value: (job.priority || '').toUpperCase() },
    { label: 'Reference', value: job.reference_number || '—' },
    { label: 'Type', value: job.type || '—' },
  ], y, pageWidth, margin, branding);

  // Dates & financials
  y = renderSection(doc, 'Schedule & Financials', [
    { label: 'Created', value: job.created_date ? new Date(job.created_date).toLocaleDateString() : '—' },
    { label: 'Due Date', value: job.due_date ? new Date(job.due_date).toLocaleDateString() : '—' },
    { label: 'Started', value: job.started_at ? new Date(job.started_at).toLocaleDateString() : '—' },
    { label: 'Completed', value: job.completed_at ? new Date(job.completed_at).toLocaleDateString() : '—' },
    { label: 'Estimated Hours', value: job.estimated_hours != null ? `${job.estimated_hours} hrs` : '—' },
    { label: 'Actual Hours', value: job.actual_hours != null ? `${job.actual_hours} hrs` : '—' },
    { label: 'Value', value: job.value != null ? `$${Number(job.value).toLocaleString()} ${job.currency || 'USD'}` : '—' },
  ], y, pageWidth, margin, branding);

  // Customer
  if (customer) {
    y = renderSection(doc, 'Customer', [
      { label: 'Name', value: customer.name },
      { label: 'Email', value: customer.email || '—' },
      { label: 'Phone', value: customer.phone || '—' },
      { label: 'Company', value: customer.company || '—' },
    ], y, pageWidth, margin, branding);
  }

  // Assignment
  y = renderSection(doc, 'Assignment', [
    { label: 'Assigned To', value: job.assigned_to || 'Unassigned' },
    { label: 'Tags', value: (job.tags || []).join(', ') || '—' },
  ], y, pageWidth, margin, branding);

  // Description
  if (job.description) {
    y += 2;
    doc.setFontSize(9);
    doc.setFont(branding.font || 'helvetica', 'bold');
    doc.setFillColor(primaryRgb.r, primaryRgb.g, primaryRgb.b);
    doc.rect(margin, y - 4, pageWidth - margin * 2, 8, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text('DESCRIPTION', margin + 3, y + 1);
    y += 10;
    doc.setFont(branding.font || 'helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(17, 24, 39);
    const wrapped = doc.splitTextToSize(job.description, pageWidth - margin * 2 - 6);
    doc.text(wrapped, margin + 3, y);
    y += wrapped.length * 5 + 6;
  }

  // Line items
  if (job.line_items && job.line_items.length > 0) {
    y += 2;
    doc.setFillColor(primaryRgb.r, primaryRgb.g, primaryRgb.b);
    doc.rect(margin, y - 4, pageWidth - margin * 2, 8, 'F');
    doc.setFontSize(9);
    doc.setFont(branding.font || 'helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('LINE ITEMS', margin + 3, y + 1);
    y += 8;

    // Table header
    const colW = [(pageWidth - margin * 2) * 0.5, (pageWidth - margin * 2) * 0.15, (pageWidth - margin * 2) * 0.15, (pageWidth - margin * 2) * 0.2];
    doc.setFillColor(240, 240, 240);
    doc.rect(margin, y - 3, pageWidth - margin * 2, 7, 'F');
    doc.setFontSize(8);
    doc.setTextColor(secondaryRgb.r, secondaryRgb.g, secondaryRgb.b);
    ['Description', 'Qty', 'Unit Price', 'Total'].forEach((h, i) => {
      const x = margin + colW.slice(0, i).reduce((a, b) => a + b, 0);
      doc.text(h, x + 2, y + 1);
    });
    y += 7;

    let total = 0;
    job.line_items.forEach((item, idx) => {
      if (idx % 2 === 0) {
        doc.setFillColor(248, 249, 250);
        doc.rect(margin, y - 3, pageWidth - margin * 2, 6, 'F');
      }
      doc.setFontSize(8);
      doc.setFont(branding.font || 'helvetica', 'normal');
      doc.setTextColor(17, 24, 39);
      const itemTotal = (item.quantity || 0) * (item.unit_price || 0);
      total += itemTotal;
      const vals = [item.description || '—', String(item.quantity || 0), `$${(item.unit_price || 0).toFixed(2)}`, `$${itemTotal.toFixed(2)}`];
      vals.forEach((v, i) => {
        const x = margin + colW.slice(0, i).reduce((a, b) => a + b, 0);
        doc.text(v, x + 2, y + 1);
      });
      y += 6;
    });

    // Total row
    doc.setFillColor(primaryRgb.r, primaryRgb.g, primaryRgb.b);
    doc.rect(margin, y - 3, pageWidth - margin * 2, 8, 'F');
    doc.setFont(branding.font || 'helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(255, 255, 255);
    doc.text('TOTAL', margin + 3, y + 2);
    const totalStr = `$${total.toFixed(2)}`;
    const totalX = margin + colW.slice(0, 3).reduce((a, b) => a + b, 0);
    doc.text(totalStr, totalX + 2, y + 2);
    y += 10;
  }

  return y;
}

// Build a Report PDF
function buildReportPDF(doc, reportData, template, pageWidth, pageHeight, margin) {
  const { branding = {} } = template;
  const primaryRgb = hexToRgb(branding.primary_color || '#111827');
  const secondaryRgb = hexToRgb(branding.secondary_color || '#6B7280');

  let y = drawHeader(doc, template, pageWidth, margin);

  // Title
  doc.setFontSize(16);
  doc.setFont(branding.font || 'helvetica', 'bold');
  doc.setTextColor(primaryRgb.r, primaryRgb.g, primaryRgb.b);
  doc.text(reportData.title || 'Report', margin, y);
  y += 5;

  if (reportData.description) {
    doc.setFontSize(9);
    doc.setFont(branding.font || 'helvetica', 'normal');
    doc.setTextColor(secondaryRgb.r, secondaryRgb.g, secondaryRgb.b);
    doc.text(reportData.description, margin, y + 3);
    y += 8;
  }
  y += 6;

  // Summary stats
  if (reportData.summary && reportData.summary.length > 0) {
    y = renderSection(doc, 'Summary', reportData.summary.map(s => ({ label: s.label, value: s.value })), y, pageWidth, margin, branding);
  }

  // Data table
  if (reportData.rows && reportData.rows.length > 0 && reportData.columns) {
    doc.setFillColor(primaryRgb.r, primaryRgb.g, primaryRgb.b);
    doc.rect(margin, y - 4, pageWidth - margin * 2, 8, 'F');
    doc.setFontSize(9);
    doc.setFont(branding.font || 'helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('DATA', margin + 3, y + 1);
    y += 8;

    const colCount = reportData.columns.length;
    const colWidth = (pageWidth - margin * 2) / colCount;

    // Table header row
    doc.setFillColor(240, 240, 240);
    doc.rect(margin, y - 3, pageWidth - margin * 2, 7, 'F');
    doc.setFontSize(8);
    doc.setFont(branding.font || 'helvetica', 'bold');
    doc.setTextColor(secondaryRgb.r, secondaryRgb.g, secondaryRgb.b);
    reportData.columns.forEach((col, i) => {
      doc.text(String(col).substring(0, 18), margin + i * colWidth + 2, y + 1);
    });
    y += 7;

    reportData.rows.forEach((row, idx) => {
      if (idx % 2 === 0) {
        doc.setFillColor(248, 249, 250);
        doc.rect(margin, y - 3, pageWidth - margin * 2, 6, 'F');
      }
      doc.setFont(branding.font || 'helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(17, 24, 39);
      reportData.columns.forEach((col, i) => {
        const val = String(row[col] ?? '—').substring(0, 20);
        doc.text(val, margin + i * colWidth + 2, y + 1);
      });
      y += 6;

      // Page break check
      if (y > pageHeight - margin - 20) {
        doc.addPage();
        y = margin + 10;
      }
    });
  }

  return y;
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const { type, data, templateId, organizationId } = body;

    if (!type || !data) {
      return Response.json({ error: 'Missing required fields: type, data' }, { status: 400 });
    }

    // Load template
    let template = {};
    if (templateId) {
      const templates = await base44.entities.PDFTemplate.filter({ id: templateId });
      template = templates[0] || {};
    } else if (organizationId) {
      const templates = await base44.entities.PDFTemplate.filter({
        organization_id: organizationId,
        is_default: true
      });
      template = templates[0] || {};
    }

    // Ensure nested objects exist
    template.branding = template.branding || {};
    template.header = template.header || {};
    template.footer = template.footer || {};
    template.layout = template.layout || {};

    const pageSize = template.layout.page_size || 'letter';
    const orientation = template.layout.orientation || 'portrait';
    const doc = new jsPDF({ orientation, unit: 'mm', format: pageSize });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;

    let contentEndY = margin;

    if (type === 'job') {
      const customer = data.customer || null;
      contentEndY = buildJobPDF(doc, data.job, customer, template, pageWidth, pageHeight, margin);
    } else if (type === 'report') {
      contentEndY = buildReportPDF(doc, data, template, pageWidth, pageHeight, margin);
    } else {
      return Response.json({ error: 'Unknown export type. Use "job" or "report"' }, { status: 400 });
    }

    // Watermark
    if (template.layout.show_watermark && template.layout.watermark_text) {
      const totalPages = doc.internal.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(48);
        doc.setTextColor(220, 220, 220);
        doc.setFont(template.branding.font || 'helvetica', 'bold');
        doc.text(template.layout.watermark_text, pageWidth / 2, pageHeight / 2, {
          angle: 45,
          align: 'center'
        });
      }
    }

    // Add footers to all pages
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      drawFooter(doc, template, pageWidth, pageHeight, margin, i, totalPages);
    }

    const pdfBytes = doc.output('arraybuffer');

    const filename = type === 'job'
      ? `job-${(data.job?.reference_number || 'export').toLowerCase()}.pdf`
      : `report-${(data.title || 'export').toLowerCase().replace(/\s+/g, '-')}.pdf`;

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Access-Control-Allow-Origin': '*',
      }
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});